#!/bin/bash

# Root
alias sudo='sudo '

# Navigation
alias ..="cd .."
alias ...="cd ../.."
alias grep="grep --color=auto"
alias la="ls -a"
alias ll="ls -al"
alias cp="cp -v -r"
alias :q="exit"
alias b="cd -"
alias za="zoxide add"

# Git
alias g="git"
alias lg="lazygit"
# cursor-agent only notifies (needs input) for terminals it recognizes. Apple_Terminal makes it emit a
# plain BEL, and blanking TMUX stops it wrapping that in passthrough so tmux's alert-bell hook sees it.
unalias agent 2>/dev/null
agent() {
  [ -n "$TMUX" ] && tmux set -w -t "$TMUX_PANE" monitor-bell on
  TERM_PROGRAM=Apple_Terminal TMUX= command agent "$@"
}
# alias gl="git log --pretty='format:%C(yellow)%h%C(reset) %C(blue)%ad%C(reset) %C(cyan)%an%C(reset) %C(white)%s%C(reset) %C(auto)%D%C(reset)' --date=iso"
alias gl="git log --graph --pretty=format:'%Cred%h%Creset - %s %Cgreen(%ar) %C(bold blue)[%an]%Creset%C(yellow)%d%Creset' --abbrev-commit"
alias gd="git diff"
alias gb="git checkout @{-1}"
alias gu="git pull"
alias gp="git push"
alias gsb="git branch --list | fzf | xargs git checkout"
alias gs="git status" # WARN: This overrides gs (GhostScript)
alias gco="git checkout"
alias gcp="git cherry-pick"
# Graphite (defined as a function in zfunctions to block `restack`)
# alias gt="ch"
# alias gtc="gt create"
# alias gsync="gt sync"
# alias gstack="gt log short --stack"

# Common commands that are just too long
alias cl="clear"
alias ka="killall"
alias ec="$EDITOR ~/.zshrc"
alias sc="source ~/.zshrc"
alias evc="$EDITOR ~/.config/nvim/init.vim"
alias v="$EDITOR"
alias vim="$EDITOR"
alias ff="firefox"
# alias google="google-chrome-stable"
alias toclip="xclip -selection c"
alias yeet="yay -Rns"
alias stdconvert="convert -resize 1240x1750 -gravity center extent 1240x1750 -units PixelsPerInch -density 150"
alias yt="youtube-dl --add-metadata -i"
alias yta="yt -x -f bestaudio/best --audio-format mp3"
alias hb="clear && $HOME/.scripts/hashbang.sh"
alias tlist="tmux list"
alias py="python manage.py shell"
alias ip="ipython"
alias notif="afplay /System/Library/Sounds/Glass.aiff -v 5"

# Axle commands
alias pipsync="python manage.py pipsync"
alias mangle="python manage.py mangledb --overwrite"
# alias migrate="python manage.py migrate"
alias makemigrations="maxmigr && python manage.py makemigrations"
alias taskconsumer="python manage.py taskconsumer"
alias taskscheduler="python manage.py taskscheduler"

# Improved commands
alias ls="lsd --color=always"
alias yay="yay"
alias python3="python"
alias fetch="neofetch --ascii_colors 4 4 --colors 11 8 8 11 8 7"
alias gccc="gcc -Wall -Werror"
alias nvide="neovide --frameless --geometry 145x45"
alias please="sudo !!"
alias plz="sudo !!"
# alias pytest="pytest --pdbcls=IPython.terminal.debugger:TerminalPdb --no-header --cov=. --cov-report=xml:coverage.xml --testmon --disable-warnings"
alias pcd="pytest --create-db"
# alert=notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history | tail -n1 | sed -e 's/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//')" \
