#! /bin/bash

ed() {
  file=$(
    du -a src |
      awk '{print $2}' |
      fzf \
        --preview 'bat --style=plain --color=always {}' \
        --preview-window noborder
  )
  if [ -n "$file" ]; then
    $EDITOR $file
  fi
}

gdel() {
  target_branch=$(git branch --list | fzf | sed 's/^[[:space:]]*//')
  if [ -z "$target_branch" ]; then
    return
  fi

  git branch -d "$target_branch"
  ret_val=$?

  if [ $ret_val -ne 0 ]; then
    echo "Are you sure you want to delete the branch?"
    response=$(echo "n\ny" | fzf)
    if [ "$response" = "y" ]; then
      git branch -D "$target_branch"
    fi
  fi
}

sqrebase() {
  current_branch=$(git branch --show-current)

  # The original base of the current branch
  if [ -z "$1" ]; then
    og_base_unparsed=$(git branch --list | fzf --prompt='From: ')
    if [ $? -ne 0 ]; then
      return
    fi
    og_base=$(echo $og_base_unparsed | sed 's/^[[:space:]]*//')
  else
    og_base=$1
  fi

  echo "alskdf"

  # The target base of the current branch
  if [ -z "$2" ]; then
    target_base_unparsed=$(git branch --list | fzf --prompt='To: ')
    if [ $? -ne 0 ]; then
      return
    fi
    target_base=$(echo $target_base_unparsed | sed 's/^[[:space:]]*//')
  else
    target_base=$1
  fi

  # Diff the head of the current branch against the target branch
  git diff $og_base..HEAD >changes.patch

  # Create a backup branch just in case
  git checkout -b "TMP/$current_branch"

  # Clean branch under same name as current branch
  git checkout $target_base
  git branch -D $current_branch
  git checkout -b $current_branch

  # Apply the changes
  git apply changes.patch
  rm changes.patch
}

dfile() {
  file=$(du -a src | awk '{print $2}' | fzf --prompt='❯ ' --pointer='❯ ')
  if [ -n "$file" ]; then
    git log --follow -p -- "$file"
  fi
}

dfunc() {
  if [ -z "$1" ]; then
    return
  fi
  func=$1
  file=$(rg --files-with-matches "^\s*def $func\(" | fzf --prompt='❯ ' --pointer='❯ ')
  if [ -n "$file" ]; then
    git log -L :$func:$file
  fi
}

maxmigr() {
  max=$(ls src/migrations | grep -E '^[0-9]+_' | tail -n 1 | cut -d '.' -f 1)
  echo $max >src/migrations/max_migration.txt
}

dirs() {
  du -d 8 \
    -I .git \
    -I .github \
    -I .swm \
    -I .pytest_cache \
    -I .venv \
    -I .vim \
    -I .vscode \
    -I __pycache__ \
    -I bin \
    -I misc \
    -I node_modules \
    ~/dev/backend \
    ~/dev/partner \
    ~/dev/interop \
    ~/dev/docs \
    ~/dev/patient \
    ~/dev/qhp-app/ \
    ~/Documents/dotfiles \
    ~/Documents/repos \
    ~/.config/nvim \
    ~/.config/tmux \
    ~/.config/zsh \
    ~/.scripts \
    2>/dev/null
}

lines() {
  cat $1 | wc -l
}

explore() {
  rg --color=always --line-number --no-heading --smart-case "" |
    fzf --ansi --delimiter : \
      --preview 'bat --style=full --color=always --highlight-line {2} {1}' \
      --preview-window '~4,+{2}+4/3,<80(up)' \
      --height 100% \
      --layout default
}

se() {
  file=$(du -a \
    ~/.wezterm.lua \
    ~/Documents/dotfiles \
    ~/.config/alacritty \
    ~/.config/nvim \
    ~/.config/tmux \
    ~/.config/zsh \
    ~/.scripts |
    awk '{print $2}' |
    fzf)
  if [ -n "$file" ]; then
    $EDITOR $file
  fi
}

sd() {
  dir=$(dirs | awk '{print $2}' | fzf)
  retVal=$?

  if [ $retVal -eq 0 ]; then
    cd $dir
  fi
}

tsd() {
  dir=$(dirs | awk '{print $2}' | fzf)
  retVal=$?

  if [ $# -gt 0 ]; then
    session=$1
  else
    session="ide"
  fi

  if [ $retVal -eq 0 ]; then
    tmux new-session -c $dir -s $session -n code -d \; \
      attach -t $session
  fi
}

sdls() {
  sd
  if [ $retVal -eq 0 ]; then
    ls
  fi
}

stat() {
  dir=$(du -d2 $(cat ~/.curQ) | grep -e 'STAT.*pset' | awk '{print $2}' | fzf --select-1)
  retVal=$?

  if [ $retVal -eq 0 ]; then
    tmux new-session -c $dir -s stat -n pset -d \; \
      attach -t stat
  fi
}

ide() {
  backend_path=~/dev/backend
  partner_path=~/dev/partner
  patient_path=~/dev/patient
  interop_path=~/dev/interop

  # dir=$(dirs | awk '{print $2}' | fzf)
  retVal=$?

  if [ $# -gt 0 ]; then
    session=$1
  else
    session="ide"
  fi

  if [ $retVal -eq 0 ]; then
    tmux new-session -c "$backend_path" -s "$session" -n "backend" -d \; \
      new-window -c "$partner_path" -n "partner" \; \
      \
      new-window -c "$backend_path" -n "servers" \; \
      split-window -c "$partner_path" -h \; \
      split-window -c "$interop_path" -v -p 90 \; \
      new-window -c "$backend_path" \; \
      new-window -c "$interop_path" -n "interop" \; \
      select-window -t "$session":backend # new-window -c "$patient_path" -n "patient" \; \
    # tmux send-keys -t "$session":0 ls C-m
    tmux attach -t $session
    # tmux new-session -s "$session" -d
    # tmux rename-window -t "$session:0" "code"
    # tmux send-keys -t "$session:0" "cd $dir && clear" C-m
    # tmux new-window -t "$session:1" -n "term"
    # tmux send-keys -t "$session:1" "cd $dir && clear" C-m
    # tmux attach -t "$session:0"
  fi
}

tat() {
  session=$(tmux ls | cut -d: -f1 | fzf --select-1 --exit-0)
  retVal=$?
  if [ $retVal -eq 0 ]; then
    tmux attach -t $session
  fi
}

tkill() {
  session=$(tmux ls | cut -d: -f1 | fzf --exit-0)
  retVal=$?
  if [ $retVal -eq 0 ]; then
    tmux kill-session -t $session
  fi
}

randp() {
  if [ -n "$1" ]; then
    dir=$1
  fi
  du -a $1 |
    grep -i -E '\.(png|jpg|jpeg|gif)$' |
    shuf -n 1000 |
    sed 's/\ |\(|\)/\\\ /g' |                               # Put a "\" before spaces
    awk '{for (i=2; i<NF; i++) printf $i " "; print $NF}' | # Remove leading numbers
    sxiv -i -t
}

pkgsizes() {
  pacman -Qei |
    gawk '/^Name/ { x = $3 }; /^Installed Size/ { sub(/Installed Size  *:/, ""); print x":" $0 }' |
    grep MiB |
    sort -k2,3nr |
    less
}

pset() {
  name="pset${1}.tex"
  cp ~/.config/zsh/templates/pset.tex $name
}

tname() {
  name=$(basename "$(pwd)")
  tmux rename-window "$name"
}

# texclean() {
#     du -a |
#     awk '{print $2}' |
#     grep -E '(\.|\_)(aux|fdb|fls|log|synctex|minted)' |
#     sed 's/.\///g' |
#     xargs rm -rf
# }
