#!/usr/bin/env sh
while read file
do
    case "$1" in
        "w")
            setbg -f "$file" & ;;
        "W")
            setbg -s "$file" & ;;
        "l")
            setbg -l "$file" & ;;
        "d")
            setbg -d "$file" & ;;
        "r")
            convert -rotate 90 "$file" "$file" ;;
        "R")
            convert -rotate -90 "$file" "$file" ;;
        "f")
            convert -flop "$file" "$file" ;;
        "y")
            echo -n "$file" | xclip -selection clipboard &&
            notify-send "$file copied to clipboard" & ;;
        "Y")
            readlink -f "$file" | xclip -selection clipboard &&
                notify-send "$(readlink -f "$file") copied to clipboard" & ;;
        "D")
            [ "$(printf "No\\nYes" | rofi -theme ~/.config/rofi/themes/nord.rasi -dmenu -i -p "Really delete?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
    esac
done
