return {
  -- {
  --   "Wansmer/symbol-usage.nvim", -- show # of references above symbol definition
  --   event = "BufReadPre", -- need run before LspAttach if you use nvim 0.9. On 0.10 use 'LspAttach'
  --   config = function()
  --     require("symbol-usage").setup()
  --   end,
  -- },

  -- {
  --   "nvimtools/none-ls.nvim",
  --   config = function()
  --     local none_ls = require("none-ls")
  --     local file = vim.fn.expand("%:p") -- Get the full path of the current file
  --
  --     -- null_ls.setup({
  --     --   sources = {
  --     --     null_ls.builtins.diagnostics.mypy.with({
  --     --       command = "mypy", -- Ensure this matches Mason's installed path for mypy
  --     --       args = {
  --     --         "--show-column-numbers",
  --     --         -- "--ignore-missing-imports", -- Adjust this based on your project needs
  --     --         "--allow-untyped-decorators",
  --     --         "--disable-error-code=ignore-without-code",
  --     --         -- "ignore-valid-type-comments=false",
  --     --         "--cache-dir=.mypy_cache",
  --     --         "--config-file",
  --     --         "pyproject.toml",
  --     --         file,
  --     --       },
  --     --     }),
  --     --   },
  --     -- })
  --   end,
  -- },
}
