#!/bin/bash
if ( xrandr | grep "DP1-1 connected" ); then
    xrandr --output eDP1 --primary --mode 2560x1440 --pos 1920x0 --rotate normal \
        --output DP1-1 --mode 1920x1080 --pos 0x0 --rotate normal 
else
    xrandr --output eDP1 --primary --mode 2560x1440 --pos 1920x0 --rotate normal \
        --output DP1-1 --off
fi

bspc wm -r

