require "user.plugins"
require "user.autocommands"
require "user.impatient"
require "user.treesitter-context"
require "user.colorscheme"
require "user.copilot"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.nvim-tree"
require "user.lualine"
-- require "user.smooth-cursor"
require "user.motion"
-- require "user.bufferline"
require "user.project"
require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.latex"
require "user.gitsigns"
require "user.goyo"
-- require "user.blame"
require "user.keymaps"
require "user.options"
