require "user.plugins"
require "user.autocommands"
require "user.colorscheme"
-- require "user.copilot"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.nvim-tree"
-- require "user.bufferline"
require "user.lualine"
require "user.motion"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.latex"
-- require "user.gitsigns"
require "user.keymaps"
require "user.options"
