require "user.packer"
require "user.plugin.autocommands"
require "user.plugin.impatient"
require "user.plugin.treesitter-context"
require "user.plugin.colorscheme"
require "user.plugin.copilot"
require "user.plugin.lsp"
require "user.plugin.telescope"
require "user.plugin.treesitter"
require "user.plugin.autopairs"
require "user.plugin.nvim-tree"
require "user.plugin.lualine"
-- require "user.plugin.smooth-cursor"
require "user.plugin.motion"
-- require "user.plugin.project"
require "user.plugin.indentline"
require "user.plugin.alpha"
require "user.plugin.whichkey"
require "user.plugin.latex"
require "user.plugin.gitsigns"
-- require "user.plugin.goyo"
-- require "user.bufferline"
-- require "user.plugin.blame"
require "user.keymaps"
require "user.options"
